# Generated by Django 5.0.6 on 2025-01-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_gmail', models.EmailField(default=None, max_length=255)),
                ('job_id', models.CharField(max_length=100, null=True)),
                ('scheduled_time', models.DateTimeField()),
            ],
        ),
    ]
